# Disable Netlify's email obfuscation which breaks inline JS
[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex"

# Disable asset optimization that mangles emails in JS
[build.processing]
  skip_processing = true
